### ISSUE TITLE
Feature embedded drawer

### ISSUE THREAD

**Issue by knownasilya** [josemarluedke/frontile#140] opened 2021-01-30 04:04 UTC
Where it takes over the parent element instead of the full page

**Comment by josemarluedke** [comment] 2021-01-30 04:32
This is already supported when using `renderInPlace ` argument.  https://frontile.dev/docs/overlays/drawer#api

**Comment by knownasilya** [comment] 2021-01-30 05:07
Get this when I use that mode
![frontile-drawer](https://user-images.githubusercontent.com/34726/106347795-152c4400-628f-11eb-8465-16fe4619989e.gif)

**Comment by josemarluedke** [comment] 2021-01-30 05:20
Ahh yeah, you need to add `position: relative` (`.relative` in Tailwindcss) to the parent.

![image](https://user-images.githubusercontent.com/230476/106348020-c1fac700-6277-11eb-9ca7-4de603a8e764.png)

**Comment by knownasilya** [comment] 2021-01-31 22:29
![frontile-drawer-rel](https://user-images.githubusercontent.com/34726/106400006-e24a9300-63e9-11eb-9798-cbc53ab3f545.gif)
Still get some weird UI issues.

**Comment by josemarluedke** [comment] 2021-02-15 19:43
Humm, this is interesting... Could it be because of the flex? I guess I need to have a reproduction to debug it.

**Comment by MichalBryxi** [comment] 2022-09-03 11:17
I think I bumped on the same. The sidebar drawer renders completely off the screen.

**Comment by josemarluedke** [comment] 2024-11-07 20:42
Closing this issue as the latest alpha has vastly different styling could have solved the issues above. Please re-open is this still makes sense.

**Closed by josemarluedke** 2024-11-07 20:42 UTC
Labels: Type: Bug
